name: doctor_appoinment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^2.0.0
  dio: ^5.6.0
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
